# Generated by tf-migrate 1.3.0

component "terraform_module" {
  source = "./terraform_modules"

  inputs = {
    "bucket_name_prefix" = var.bucket_name_prefix
    "default_tags"       = var.default_tags
    "enaable_versioning" = var.enaable_versioning
    "force_destroy"      = var.force_destroy
  }


  providers = {
    aws    = provider.aws.this
    local  = provider.local.this
    random = provider.random.this
    time   = provider.time.this
  }
}


