# Generated by tf-migrate 1.3.0


# Note on stacks authentication:
# tf-migrate cannot generate stack authentication, this needs to be manually added before execute
# More on authentication - https://developer.hashicorp.com/terraform/language/stacks/deploy/authenticate

deployment "hello-s3-bucket-VCS-deployment" {
  inputs = {
    default_tags = {
      CanDelete = "true"
      CreatedBy = "Terraform"
      Project   = "StacksModularizationTest"
    }
    enaable_versioning = null # tf-migrate could not associate a value for this variable, adding nil PLACEHOLDER and this has to be set manually before execute
    bucket_name_prefix = null # tf-migrate could not associate a value for this variable, adding nil PLACEHOLDER and this has to be set manually before execute
    force_destroy      = null # tf-migrate could not associate a value for this variable, adding nil PLACEHOLDER and this has to be set manually before execute
  }
  import = true
}



