# Generated by tf-migrate 1.3.0


# Note on stacks authentication:
# tf-migrate cannot generate stack authentication, this needs to be manually added before execute
# More on authentication - https://developer.hashicorp.com/terraform/language/stacks/deploy/authenticate

deployment "hello-s3-bucket-VCS-deployment" {
  inputs = {
    default_tags = {
      CanDelete = "true"
      CreatedBy = "Terraform"
      Project   = "StacksModularizationTest"
    }
    enaable_versioning = true
    bucket_name_prefix = "stacksmodtest"
    force_destroy      = true
  }
  import = true
}



