# Generated by tf-migrate 1.3.0

output "s3_bucket_id" {
  description = "The name of the S3 bucket"
  value       = component.terraform_module.s3_bucket_id
  type        = string
}

output "s3_bucket_domain_name" {
  description = "The domain name of the S3 bucket"
  value       = component.terraform_module.s3_bucket_domain_name
  type        = string
}

output "s3_bucket_region" {
  description = "The region of the S3 bucket"
  value       = component.terraform_module.s3_bucket_region
  type        = string
}

output "aws_availability_zones" {
  description = "The list of availability zones"
  value       = component.terraform_module.aws_availability_zones
  type        = list(string)
}

output "s3_object_url" {
  description = "The URL of the uploaded JSON file in S3"
  value       = component.terraform_module.s3_object_url
  type        = string
}

output "last_modified" {
  description = "The last modified time of the uploaded JSON file"
  value       = component.terraform_module.last_modified
  type        = string
}

output "s3_bucket_arn" {
  description = "The ARN of the S3 bucket"
  value       = component.terraform_module.s3_bucket_arn
  type        = string
}

