# Generated by tf-migrate 1.3.0

required_providers {
  aws = {
    source  = "hashicorp/aws"
    version = ">= 6.5.0"
  }

  random = {
    source  = "hashicorp/random"
    version = "~> 3.0"
  }

  time = {
    source  = "hashicorp/time"
    version = "~> 0.7"
  }
}

provider "aws" "this" {
  config {
    region = "ap-south-1"
  }
}

provider "random" "this" {
}
provider "time" "this" {
}
